### ISSUE TITLE
Change Course Name option in course edit

### ISSUE THREAD

**Issue by avkrakowski** [avkrakowski/lt-course-registration#3]
I need to remove the -Sinfionetta in the original courses as we now have new course codes specifically for sinfionetta.
example
	947101H: H Adv Orchestra I-Sinfionetta (Music)

**Comment by heymrhayes** [comment]
The data that you edit on that page is the "course year" data, not the base course data, so adding that editing feature isn't the 5 minute job it might otherwise be.

I've updated those course names for now.

I'll create a new issue indicating that we need to add a "course edit" feature to the app.

@avkrakowski
